/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

//module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
//};
/**
 * This sidebar file is auto-generated by Docusaurus.
 * It will automatically create categories and subcategories
 * based on your folder structure and index.md files.
 */

module.exports = {
  iso13485: [
    {
      type: 'autogenerated',
      dirName: 'calidad-iso13485', // carpeta raíz de ISO 13485
    },
  ],
  iso27001: [
    {
      type: 'autogenerated',
      dirName: 'seguridad-iso27001', // carpeta raíz de ISO 27001
    },
  ],
};
